### ISSUE TITLE
压缩后的数据大小变得更大了

### ISSUE THREAD

**Issue by dgx20631920318** [lingmoyun/minilzo-java#1]
您好，我使用以下方式进行压缩和解压后，发现压缩后的数据大小变得更大了，是我的使用方法有误吗？
![image](https://github.com/lingmoyun/minilzo-java/assets/122373007/b683cdd0-3f60-4606-95a3-33ef47e49d15)

**Comment by dgx20631920318** [comment]
``` java
    @org.junit.jupiter.api.Test
    public void TestMiniLZO() {
        byte[] origin = new byte[60000];
        for (int i = 0; i < 60000; i++) {
            origin[i] = (byte) (new Random().nextInt(256) - 127);
        }
        System.out.println("origin.length:" + origin.length);
        byte[] compressed = MiniLZO.compress(origin);
        System.out.println("compressed.length:" + compressed.length);
        byte[] decompressed = MiniLZO.decompress(compressed);
        System.out.println("decompressed.length:" + decompressed.length);
    }
```

**Comment by winfordguo** [comment]
压缩后再解压得到的数据与原始数据一致就没问题的。

**Comment by dgx20631920318** [comment]
好的 感谢回复，我后续又进行了测试，压缩后的大小和数据的分布有关，随机性越大压缩效果就越差
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "Winford"; 
Date: 2023年9月6日(星期三) 上午9:31
To: "lingmoyun/minilzo-java"; 
Cc: ***@***.***>; "Author"; 
Subject: Re: [lingmoyun/minilzo-java] 压缩后的数据大小变得更大了 (Issue #1)

&nbsp;


 
压缩后再解压得到的数据与原始数据一致就没问题的。

**Comment by winfordguo** [comment]
好的。
